### ISSUE TITLE
los context_attributes no estan pasando al WebGLRenderer

### ISSUE THREAD

**Issue by keilyn3d** [ohzinteractive/core#15]
Creo que tienen que agregar estas lineas en Graphics.js:

<img width="684" alt="Screen Shot 2023-05-19 at 1 02 09 AM" src="https://github.com/ohzinteractive/core/assets/7438027/43ae2719-6292-453c-b6da-097972643a16">

tambien me pueden decir si hay otra forma de modificar el WebGLRenderer en un proyecto.

**Comment by fedegratti** [comment]
Gracias por esto, ahi actualizamos el core para corregirlo.

Ahora en el Api.js vas a encontrar 3 sets de atributos:
- core_attributes son atributos para nuestro core (no corresponden ni a threejs, ni al contexto webgl)
- context_attributes son los atributos nativos del contexto webgl: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
- threejs_attributes son atributos que recibe la clase `WebGLRenderer` de Threejs. threejs_attributes toma los valores de context_attributes y agrega los propios de Threejs (como logarithmicDepthBuffer).

<img width="711" alt="image" src="https://github.com/ohzinteractive/core/assets/15077532/7e1d11ad-a6ce-46e7-b272-d7cc42d47bf4">
